### PR TITLE
Don't hard code header locations, use <SDL2/SDL.h>

### PR DESCRIPTION
**Pull request by pcbeard**
This gives us the flexibility of finding headers wherever they
maybe installed. Currently I'm creating symlinks to the homebrew
build of libSDL2 /usr/local/include and /usr/local/lib.

### Description

To be able to build against headers installed *EITHER* in /usr/include *OR* /usr/local/{include,lib}, simply reference <SDL2/SDL_*.h>. On Linux, this means the headers will be found in /usr/include if they SDL development package is installed via apt (on Debian), or in /usr/local/include (suitably symlinked) when using some alternative package manager such as Homebrew.

### Detailed Design

No new APIs, just some header file changes.

### Documentation

*How has the new feature been documented? 
Have the relevant portions of the guides in the Documentation folder been updated in addition to symbol-level documentation?*

### Testing

*How is the new feature tested?

Tested building on WSL Debian distribution.

### Performance

N/A

### Source Impact

It should simplify things.

### Checklist

- [x] I've read the [Contribution Guidelines](https://github.com/ctreffs/SwiftSDL2/blob/master/CONTRIBUTING.md)
- [x] I've followed the coding style of the rest of the project.
- [ ] I've added tests covering all new code paths my change adds to the project (to the extent possible).
- [ ] I've added benchmarks covering new functionality (if appropriate).
- [ ] I've verified that my change does not break any existing tests or introduce unexpected benchmark regressions.
- [ ] I've updated the documentation (if appropriate).

### CODE REVIEW

**Comment by ctreffs** [comment]
Great addition - let's see what the pipeline says then we merge it 🙂 
Thank you for your contribution and the good explanation 👍

**Comment by ctreffs** [comment]
@pcbeard could you have a look at the Linux CI - we're getting an error there:

```sh
swift test
5
'CSDL2' sdl2.pc: warning: prohibited flag(s): -D_REENTRANT
6
[1/6] Compiling CSDL2Tests CSDL2Tests.swift
7
<module-includes>:1:10: note: in file included from <module-includes>:1:
8
#include "shims.h"
9
         ^
10
/__w/SwiftSDL2/SwiftSDL2/Sources/CSDL2/shims.h:13:11: note: in file included from /__w/SwiftSDL2/SwiftSDL2/Sources/CSDL2/shims.h:13:
11
        #include "other_platforms.h"
12
                 ^
13
/__w/SwiftSDL2/SwiftSDL2/Sources/CSDL2/other_platforms.h:39:10: error: 'SDL2/SDL_sensor.h' file not found
14
#include <SDL2/SDL_sensor.h>
15
         ^
16
/__w/SwiftSDL2/SwiftSDL2/Sources/CSDL2Wrapped/CSDL2Wrapped.swift:9:19: error: could not build C module 'CSDL2'
17
@_exported import CSDL2
18
                  ^
19
error: fatalError
20
make: *** [test] Error 1
21
Makefile:14: recipe for target 'test' failed
22
Error: Process completed with exit code 2.
```

**Comment by pcbeard** [comment]
How does your CI environment install the SDL2 library?

**Comment by pcbeard** [comment]
I looked over the logs, I guess the file <SDL2/SDL_sensor.h> isn't part of the version of SDL2 installed on your builder? If we were building with clang, we could use __has_include(). I will try removing that header from the file to see if that fixes the build.

**Comment by pcbeard** [comment]
My earlier change was based on copying the apple_macOS.h header file. This time I just modified the current one, which clearly leaves out SDL_sensor.h. I feel like we need a better solution for this. Granted this is a somewhat obscure header file; looks like it's for getting accelerometer data, but this header file does exist in v2.0.9.

**Review by ctreffs — APPROVED** [review]

**Pull request merged**
